### PR TITLE
Implement useSSL connection config option

### PR DESCRIPTION
**Pull request by rsolano**
Adds the `useSsl` option available via the [Java ArangoDB driver](https://www.arangodb.com/docs/stable/drivers/java-reference-setup.html).

### CODE REVIEW

**Review by jaredpetersen — CHANGES_REQUESTED** [review]
Looks great! Just update the patch version in `pom.xml` and we can get this merged 🚀

**Review by jaredpetersen — DISMISSED** [review]

**Comment by jaredpetersen** [comment]
After you merge this, I'll try to get this fully deployed to Maven Central as soon as I can. The process is partially automated but Maven Central still requires button clicks in a UI unless you use a specialized maven plugin.

**Comment by rsolano** [comment]
Sounds good, thanks! Looks like you'll have to merge it for me though.

**Comment by jaredpetersen** [comment]
I was wondering if that was the case... Sorry!

Ah, shoot. One more change that I forgot about. Please update the CHANGELOG. Something simple like:

```
## [1.0.7] - 2020-03-10
### Changed
- Added support for SSL
```

The GitHub release is auto-generated so keeping track of changes in the CHANGELOG is the best way of communicating this sort of thing.

Thanks for your contribution and sorry for the inconvenience 😓

**Comment by rsolano** [comment]
Absolutely, no worries and thank you for making this connector!

**Review by jaredpetersen — APPROVED** [review]

**Comment by jaredpetersen** [comment]
@rsolano Your change has been deployed to maven central. Thanks again! 🚀

**Pull request merged**
